import type { Roadmap } from '../types'

export const aiMlRoadmap: Roadmap = {
  id: 'ai-ml',
  title: 'AI / Machine Learning',
  tagline: 'From Python basics to building real ML models in 14 weeks',
  icon: 'Brain',
  color: '#a78bfa',
  accentGradient: 'from-violet-500 to-purple-400',
  totalWeeks: 14,
  difficulty: 'intermediate',
  averageSalary: '₹5–12 LPA (fresher)',
  jobOpenings: '45,000+ open roles in India',

  phases: [
    {
      id: 'phase-1',
      phase: 1,
      title: 'Python & Math Foundations',
      subtitle: 'Python · NumPy · Linear Algebra',
      duration: 'Week 1–3',
      icon: 'Code2',
      color: 'violet',
      goal: 'I can write clean Python and understand the math behind ML',
      topics: [
        'Python: data types, loops, functions, OOP basics',
        'NumPy arrays, broadcasting, matrix operations',
        'Pandas DataFrames: load, clean, transform data',
        'Linear algebra: vectors, matrices, dot product, eigenvalues',
        'Statistics & probability: mean, variance, distributions, Bayes theorem',
        'Matplotlib & Seaborn for data visualization',
      ],
      resources: [
        { title: 'Python for Everybody – Coursera (Audit Free)', url: 'https://coursera.org/specializations/python', type: 'course', free: true },
        { title: '3Blue1Brown – Essence of Linear Algebra', url: 'https://youtube.com/playlist?list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab', type: 'video', free: true },
        { title: 'Kaggle – Python & Pandas Courses', url: 'https://kaggle.com/learn', type: 'course', free: true },
        { title: 'StatQuest with Josh Starmer', url: 'https://youtube.com/@statquest', type: 'video', free: true },
      ],
      projects: [
        {
          title: 'Exploratory Data Analysis (EDA) on Real Dataset',
          description: 'Pick any dataset from Kaggle (Titanic, House Prices, Netflix). Clean, analyze, and visualize 10 insights.',
          skills: ['Pandas', 'Matplotlib', 'Seaborn', 'NumPy'],
          difficulty: 'beginner',
          estimatedTime: '10–15 hours',
        },
      ],
      milestone: 'Published EDA notebook on Kaggle with 5+ visualizations',
    },
    {
      id: 'phase-2',
      phase: 2,
      title: 'Classical ML Algorithms',
      subtitle: 'Scikit-learn · Regression · Classification · Clustering',
      duration: 'Week 4–7',
      icon: 'GitBranch',
      color: 'purple',
      goal: 'I can train, evaluate, and tune ML models on real datasets',
      topics: [
        'Supervised learning: Linear Regression, Logistic Regression',
        'Decision Trees, Random Forests, XGBoost',
        'K-Means Clustering, DBSCAN',
        'Feature engineering & selection',
        'Train/val/test splits, cross-validation',
        'Model evaluation: confusion matrix, ROC-AUC, RMSE',
        'Hyperparameter tuning with GridSearchCV',
        'Scikit-learn pipelines',
      ],
      resources: [
        { title: 'Scikit-learn Official Documentation', url: 'https://scikit-learn.org/stable/user_guide.html', type: 'article', free: true },
        { title: 'Hands-On ML with Scikit-Learn & TensorFlow (Book)', url: 'https://oreilly.com/library/view/hands-on-machine-learning/9781492032632/', type: 'book', free: false },
        { title: 'Kaggle – Intro to ML & Intermediate ML', url: 'https://kaggle.com/learn/intro-to-machine-learning', type: 'course', free: true },
        { title: 'fast.ai – Practical Deep Learning', url: 'https://course.fast.ai', type: 'course', free: true },
      ],
      projects: [
        {
          title: 'House Price Prediction',
          description: 'Build a regression model to predict house prices. Feature engineering, model comparison, deployment on Streamlit.',
          skills: ['Scikit-learn', 'Feature Engineering', 'Streamlit'],
          difficulty: 'intermediate',
          estimatedTime: '20–30 hours',
        },
        {
          title: 'Customer Churn Classifier',
          description: 'Binary classification on telecom dataset. Build XGBoost model, explain predictions with SHAP values.',
          skills: ['XGBoost', 'SHAP', 'Pandas', 'Scikit-learn'],
          difficulty: 'intermediate',
          estimatedTime: '15–25 hours',
        },
      ],
      milestone: '2 ML projects on GitHub with documented notebooks and Streamlit demo',
    },
    {
      id: 'phase-3',
      phase: 3,
      title: 'Deep Learning & Neural Networks',
      subtitle: 'PyTorch · CNNs · NLP Basics · Transfer Learning',
      duration: 'Week 8–11',
      icon: 'Cpu',
      color: 'fuchsia',
      goal: 'I can build and train neural networks for vision and NLP tasks',
      topics: [
        'Neural network fundamentals: forward/backward pass, gradient descent',
        'PyTorch tensors, autograd, nn.Module',
        'CNNs for image classification',
        'Transfer learning with pretrained models (ResNet, EfficientNet)',
        'NLP basics: tokenization, embeddings, sentiment analysis',
        'Hugging Face Transformers (BERT, GPT-2 fine-tuning)',
        'Model saving, loading, and serving',
        'Google Colab & GPU acceleration',
      ],
      resources: [
        { title: 'fast.ai – Practical Deep Learning Part 1', url: 'https://course.fast.ai', type: 'course', free: true },
        { title: 'PyTorch Official Tutorials', url: 'https://pytorch.org/tutorials', type: 'article', free: true },
        { title: 'Hugging Face Course', url: 'https://huggingface.co/course', type: 'course', free: true },
        { title: 'Andrej Karpathy – Neural Networks Zero to Hero', url: 'https://youtube.com/@AndrejKarpathy', type: 'video', free: true },
      ],
      projects: [
        {
          title: 'Image Classifier (Your Own Category)',
          description: 'Train a CNN to classify images you scrape. Fine-tune ResNet50. Deploy with FastAPI + Streamlit.',
          skills: ['PyTorch', 'Transfer Learning', 'FastAPI', 'Streamlit'],
          difficulty: 'advanced',
          estimatedTime: '25–40 hours',
        },
        {
          title: 'Sentiment Analysis API',
          description: 'Fine-tune DistilBERT on a custom dataset. Build a REST API endpoint that returns sentiment + confidence score.',
          skills: ['Hugging Face', 'BERT', 'FastAPI', 'Python'],
          difficulty: 'advanced',
          estimatedTime: '20–35 hours',
        },
      ],
      milestone: 'Both projects deployed as APIs, linked in resume and LinkedIn',
    },
    {
      id: 'phase-4',
      phase: 4,
      title: 'MLOps & Internship Prep',
      subtitle: 'MLflow · Docker · Resume · Research',
      duration: 'Week 12–14',
      icon: 'Rocket',
      color: 'emerald',
      goal: 'I can manage the full ML lifecycle and communicate my work professionally',
      topics: [
        'MLflow experiment tracking',
        'Docker containers for ML apps',
        'GitHub Actions for CI/CD',
        'Writing ML project READMEs that impress',
        'Reading and summarizing ML papers (arXiv)',
        'Kaggle competition participation',
        'Interview prep: ML fundamentals questions',
      ],
      resources: [
        { title: 'MLflow Documentation', url: 'https://mlflow.org/docs/latest/index.html', type: 'article', free: true },
        { title: 'Docker for ML – Towards Data Science', url: 'https://towardsdatascience.com', type: 'article', free: true },
        { title: 'Kaggle Competitions (Start with Playground)', url: 'https://kaggle.com/competitions', type: 'tool', free: true },
      ],
      projects: [],
      milestone: 'Kaggle profile with 1 competition submission, 3 ML projects on GitHub',
    },
  ],

  internshipGuide: [
    {
      step: 1,
      title: 'Start with Research Internships',
      description: 'University AI labs are a goldmine for beginners. Email professors with your Kaggle profile and GitHub. Most say yes if you show genuine curiosity and one solid project.',
    },
    {
      step: 2,
      title: 'Target ML Platforms',
      description: 'AI startups, ML SaaS, and data analytics companies are the best hunting grounds for ML internships.',
      platforms: [
        { name: 'Internshala', url: 'https://internshala.com' },
        { name: 'LinkedIn', url: 'https://linkedin.com/jobs' },
        { name: 'Wellfound', url: 'https://wellfound.com' },
        { name: 'Kaggle Jobs', url: 'https://kaggle.com/jobs' },
        { name: 'AI Jobs (aijobs.net)', url: 'https://aijobs.net' },
      ],
    },
    {
      step: 3,
      title: 'Cold Email Researchers',
      description: 'Find ML researchers on Google Scholar. Email them after reading one of their papers. This shows genuine interest.',
      template: `Hi Professor/Dr. [Name], I recently read your paper on [Topic] and found your approach to [specific method] particularly insightful. I'm a [year] student working on [related project]. Would you consider a research internship or collaboration opportunity?`,
    },
  ],

  resumeTips: [
    'Lead with a strong "Skills" section — list frameworks, libraries, tools',
    'For each project, mention dataset size, accuracy metrics, and deployment status',
    'Include Kaggle rank/medals if applicable',
    'Mention any published notebooks with view counts',
    'Highlight contributions to open-source ML repos if any',
    'Add a "Research Interests" section to signal long-term direction',
  ],

  linkedInTips: [
    'Share every model you build — even imperfect ones. Document the journey.',
    'Follow and engage with AI researchers and ML practitioners',
    'Write short posts explaining ML concepts in simple terms',
    'Join and post in ML-focused LinkedIn groups',
  ],
}
