import type { Roadmap } from '../types'

export const appDevelopmentRoadmap: Roadmap = {
  id: 'app-development',
  title: 'App Development',
  tagline: 'Build cross-platform mobile apps and ship to the Play Store — 12 weeks',
  icon: 'Smartphone',
  color: '#fb923c',
  accentGradient: 'from-orange-500 to-amber-400',
  totalWeeks: 12,
  difficulty: 'intermediate',
  averageSalary: '₹4–9 LPA (fresher)',
  jobOpenings: '40,000+ open roles in India',

  phases: [
    {
      id: 'phase-1',
      phase: 1,
      title: 'Dart & Flutter Foundations',
      subtitle: 'Dart Language · Flutter Widgets · State',
      duration: 'Week 1–3',
      icon: 'Code2',
      color: 'orange',
      goal: 'I can build multi-screen Flutter apps with proper state management',
      topics: [
        'Dart: variables, functions, classes, null safety, async/await',
        'Flutter widget tree: Stateless vs Stateful widgets',
        'Layout widgets: Column, Row, Stack, Container, Expanded',
        'Navigation: Navigator 2.0 and go_router',
        'State management: Provider (start here), then Riverpod',
        'Flutter themes and custom typography',
        'Handling forms and user input',
      ],
      resources: [
        { title: 'Flutter Official Docs – flutter.dev', url: 'https://flutter.dev/docs', type: 'article', free: true },
        { title: 'Dart Official Tour', url: 'https://dart.dev/guides/language/language-tour', type: 'article', free: true },
        { title: 'Flutter & Dart – The Complete Guide (Udemy – buy on sale)', url: 'https://udemy.com', type: 'course', free: false },
        { title: 'FilledStacks YouTube Channel', url: 'https://youtube.com/@FilledStacks', type: 'video', free: true },
        { title: 'Flutter Community – Medium', url: 'https://medium.com/flutter', type: 'article', free: true },
      ],
      projects: [
        {
          title: 'Expense Tracker App',
          description: 'Multi-screen Flutter app to add, categorize, and visualize personal expenses. Use Provider for state and SharedPreferences for persistence.',
          skills: ['Flutter', 'Dart', 'Provider', 'SharedPreferences'],
          difficulty: 'intermediate',
          estimatedTime: '15–25 hours',
        },
      ],
      milestone: 'App running on physical device + emulator, APK exportable',
    },
    {
      id: 'phase-2',
      phase: 2,
      title: 'Backend Integration & Firebase',
      subtitle: 'Firebase · REST APIs · Auth · Firestore',
      duration: 'Week 4–7',
      icon: 'Cloud',
      color: 'amber',
      goal: 'I can build apps with real backends, authentication, and live data',
      topics: [
        'Firebase Auth (Google, email/password)',
        'Cloud Firestore: documents, collections, real-time listeners',
        'Firebase Storage for file uploads',
        'HTTP package: GET/POST with REST APIs',
        'dio package for advanced API calls',
        'Push notifications with Firebase Messaging',
        'Error handling and loading states',
      ],
      resources: [
        { title: 'Firebase Flutter Codelab', url: 'https://firebase.google.com/codelabs/firebase-get-to-know-flutter', type: 'course', free: true },
        { title: 'Flutter Fire Documentation', url: 'https://firebase.flutter.dev', type: 'article', free: true },
        { title: 'Fireship.io – Firebase + Flutter Videos', url: 'https://youtube.com/@Fireship', type: 'video', free: true },
      ],
      projects: [
        {
          title: 'Social Media Clone (Simplified)',
          description: 'Instagram-like app: sign up/in, create posts with images, like/comment, view feed. Full Firebase backend.',
          skills: ['Flutter', 'Firebase', 'Cloud Firestore', 'Storage', 'Auth'],
          difficulty: 'advanced',
          estimatedTime: '30–50 hours',
        },
        {
          title: 'Real-Time Chat App',
          description: 'WhatsApp-like group and direct messaging app with Firestore real-time updates, typing indicators, and push notifications.',
          skills: ['Flutter', 'Firestore', 'Firebase Messaging'],
          difficulty: 'advanced',
          estimatedTime: '25–40 hours',
        },
      ],
      milestone: 'Two full-stack Flutter apps in GitHub with Firebase integration',
    },
    {
      id: 'phase-3',
      phase: 3,
      title: 'Publishing & Advanced Topics',
      subtitle: 'Play Store · App Store · Performance · Animations',
      duration: 'Week 8–11',
      icon: 'Upload',
      color: 'yellow',
      goal: 'I have a live app on the Play Store and understand Flutter internals',
      topics: [
        'Flutter animations: AnimatedContainer, Hero, Lottie',
        'Performance: lazy loading, image caching, list optimization',
        'Flutter Flavors for dev/staging/prod environments',
        'Google Play Store: app signing, ASO, screenshots',
        'Apple App Store basics (if available)',
        'Code architecture: clean architecture / MVVM',
        'Unit and widget testing in Flutter',
      ],
      resources: [
        { title: 'Flutter Performance Best Practices', url: 'https://docs.flutter.dev/perf/best-practices', type: 'article', free: true },
        { title: 'Lottie for Flutter', url: 'https://pub.dev/packages/lottie', type: 'tool', free: true },
        { title: 'pub.dev – Flutter Package Registry', url: 'https://pub.dev', type: 'tool', free: true },
      ],
      projects: [],
      milestone: 'App published on Google Play (even with 1–10 downloads)',
    },
    {
      id: 'phase-4',
      phase: 4,
      title: 'Internship Launch',
      subtitle: 'Portfolio · Play Store · Interview Prep',
      duration: 'Week 12',
      icon: 'Rocket',
      color: 'emerald',
      goal: 'My Play Store listing and GitHub portfolio get me interview calls',
      topics: [
        'Flutter interview questions (widget lifecycle, setState vs Provider)',
        'Demonstrating app to interviewers: screen recording + Loom',
        'Freelance as alternative entry (Fiverr, Toptal)',
      ],
      resources: [
        { title: 'Flutter Interview Questions – GitHub Awesome List', url: 'https://github.com/Raj27p/flutter-interview-questions', type: 'article', free: true },
      ],
      projects: [],
      milestone: '10 applications sent, 1 live Play Store app in resume',
    },
  ],

  internshipGuide: [
    {
      step: 1,
      title: 'Your App IS Your Resume',
      description: 'A published Play Store app beats any certification. Even 10 downloads is legitimate. Put the Play Store URL directly on your resume.',
    },
    {
      step: 2,
      title: 'Where to Apply',
      description: 'Apply on these top platforms for best conversions',
      platforms: [
        { name: 'Internshala', url: 'https://internshala.com' },
        { name: 'LinkedIn', url: 'https://linkedin.com/jobs' },
        { name: 'Wellfound', url: 'https://wellfound.com' },
        { name: 'Naukri.com', url: 'https://naukri.com' },
        { name: 'Freelancer.com', url: 'https://freelancer.com' },
      ],
    },
    {
      step: 3,
      title: 'Target Mobile-First Startups',
      description: 'EdTech, HealthTech, FinTech startups all need Flutter developers. They move fast and give real responsibility.',
      template: `Hi [Name], I'm a Flutter developer (student) who just shipped my first app on the Play Store — [App Name]. I'd love to contribute to [Company]'s mobile team, even as an unpaid/low-stipend intern. Play Store link: [link] | GitHub: [link]`,
    },
  ],

  resumeTips: [
    'List the Play Store URL of your published app — it\'s your biggest credibility signal',
    'List: Flutter, Dart, Firebase, REST APIs, Provider/Riverpod',
    'Show number of downloads or ratings if above zero',
    'Screenshot your best app screen and include it in portfolio PDF',
    'Mention: Git, Android Studio, Xcode (even basic familiarity)',
  ],

  linkedInTips: [
    'Post a short screen recording of your app every time you ship a new feature',
    'Write about your Flutter learning journey — highly searched content',
    'Engage in Flutter communities on Discord and Reddit (r/FlutterDev)',
    'Tag your app posts with #Flutter #MobileAppDevelopment #Android',
  ],
}
