import type { Roadmap } from '../types'

export const dataAnalyticsRoadmap: Roadmap = {
  id: 'data-analytics',
  title: 'Data Analytics',
  tagline: 'Turn raw data into business decisions — internship-ready in 10 weeks',
  icon: 'BarChart3',
  color: '#34d399',
  accentGradient: 'from-emerald-500 to-teal-400',
  totalWeeks: 10,
  difficulty: 'beginner-friendly',
  averageSalary: '₹3–7 LPA (fresher)',
  jobOpenings: '60,000+ open roles in India',

  phases: [
    {
      id: 'phase-1',
      phase: 1,
      title: 'Data Foundations',
      subtitle: 'Excel · SQL · Python Basics',
      duration: 'Week 1–3',
      icon: 'Table',
      color: 'emerald',
      goal: 'I can query, clean, and analyze data using SQL and Python',
      topics: [
        'Excel: VLOOKUP, pivot tables, conditional formatting, dashboards',
        'SQL: SELECT, WHERE, GROUP BY, JOIN, subqueries, window functions',
        'Python basics for data: Pandas read_csv, head, describe, value_counts',
        'Data types: structured vs unstructured, wide vs long format',
        'Data cleaning: handling nulls, duplicates, outliers',
        'Exploratory Data Analysis (EDA) workflow',
      ],
      resources: [
        { title: 'Mode Analytics SQL Tutorial', url: 'https://mode.com/sql-tutorial', type: 'course', free: true },
        { title: 'Kaggle – Pandas & SQL Courses', url: 'https://kaggle.com/learn', type: 'course', free: true },
        { title: 'Excel for Data Analysis – ExcelJet', url: 'https://exceljet.net', type: 'article', free: true },
        { title: 'SQLBolt – Interactive SQL', url: 'https://sqlbolt.com', type: 'course', free: true },
      ],
      projects: [
        {
          title: 'Sales Data Analysis',
          description: 'Analyze 1–2 years of retail sales data with SQL + Pandas. Find top products, seasonal trends, and customer segments.',
          skills: ['SQL', 'Pandas', 'Excel'],
          difficulty: 'beginner',
          estimatedTime: '12–18 hours',
        },
      ],
      milestone: 'SQL queries and EDA notebook published on GitHub',
    },
    {
      id: 'phase-2',
      phase: 2,
      title: 'Data Visualization & Storytelling',
      subtitle: 'Tableau · Power BI · Matplotlib · Storytelling',
      duration: 'Week 4–6',
      icon: 'PieChart',
      color: 'teal',
      goal: 'I can build dashboards and communicate data insights visually',
      topics: [
        'Tableau Desktop basics: charts, filters, calculated fields',
        'Power BI: data import, relationships, DAX basics, reports',
        'Matplotlib & Seaborn advanced charts',
        'Data storytelling frameworks (what → so what → now what)',
        'Chart selection: when to use bar, line, scatter, heatmap',
        'Dashboard design principles for executives',
      ],
      resources: [
        { title: 'Tableau Public (Free)', url: 'https://public.tableau.com', type: 'tool', free: true },
        { title: 'Power BI Desktop (Free)', url: 'https://powerbi.microsoft.com', type: 'tool', free: true },
        { title: 'Data Visualization Society', url: 'https://datavizproject.com', type: 'article', free: true },
        { title: 'Storytelling with Data (Book)', url: 'https://storytellingwithdata.com', type: 'book', free: false },
      ],
      projects: [
        {
          title: 'COVID-19 / Cricket / IPL Data Dashboard',
          description: 'Build an interactive Tableau or Power BI dashboard with 5+ charts. Publish on Tableau Public.',
          skills: ['Tableau', 'Power BI', 'Data Storytelling'],
          difficulty: 'intermediate',
          estimatedTime: '15–25 hours',
        },
      ],
      milestone: 'Dashboard live on Tableau Public with shareable link',
    },
    {
      id: 'phase-3',
      phase: 3,
      title: 'Advanced Analytics & Statistics',
      subtitle: 'A/B Testing · Statistical Inference · Forecasting',
      duration: 'Week 7–9',
      icon: 'TrendingUp',
      color: 'cyan',
      goal: 'I can apply statistical thinking to real business problems',
      topics: [
        'Hypothesis testing: t-test, chi-square, p-values',
        'A/B testing design and analysis',
        'Regression analysis for prediction',
        'Time series basics: trend, seasonality, forecasting',
        'Google Analytics / Mixpanel basics for product analytics',
        'Business metrics: CAC, LTV, churn rate, NPS, retention cohorts',
      ],
      resources: [
        { title: 'Khan Academy – Statistics & Probability', url: 'https://khanacademy.org/math/statistics-probability', type: 'course', free: true },
        { title: 'Lean Analytics (Book)', url: 'https://leananalyticsbook.com', type: 'book', free: false },
        { title: 'Google Analytics Academy', url: 'https://analytics.google.com/analytics/academy', type: 'course', free: true },
      ],
      projects: [
        {
          title: 'E-commerce A/B Test Analysis',
          description: 'Analyze a simulated A/B test dataset. Determine statistical significance, compute confidence intervals, and make a business recommendation.',
          skills: ['Statistics', 'Python', 'Pandas', 'Hypothesis Testing'],
          difficulty: 'advanced',
          estimatedTime: '18–28 hours',
        },
      ],
      milestone: '3 projects in GitHub, 1 dashboard on Tableau Public, ready for interviews',
    },
    {
      id: 'phase-4',
      phase: 4,
      title: 'Internship Launch',
      subtitle: 'Resume · Portfolio · Analytics Interviews',
      duration: 'Week 10',
      icon: 'Rocket',
      color: 'emerald',
      goal: 'I am actively interviewing for data analyst internship roles',
      topics: [
        'Resume for data analyst: technical skills section, project metrics',
        'SQL interview prep: 30 common questions',
        'Business case interviews: STAR method',
        'Portfolio: Kaggle, Tableau Public, GitHub, Notion',
      ],
      resources: [
        { title: 'StrataScratch – SQL Interview Practice', url: 'https://stratascratch.com', type: 'tool', free: true },
        { title: 'DataLemur – Data Science Interview', url: 'https://datalemur.com', type: 'tool', free: true },
      ],
      projects: [],
      milestone: '10 applications sent, SQL interview practice complete',
    },
  ],

  internshipGuide: [
    {
      step: 1,
      title: 'Target Analytics-Heavy Industries First',
      description: 'E-commerce, fintech, edtech, and SaaS companies have dedicated analytics teams and frequently hire student interns.',
    },
    {
      step: 2,
      title: 'Best Platforms for Data Internships',
      description: 'Apply on these target platforms',
      platforms: [
        { name: 'Internshala', url: 'https://internshala.com' },
        { name: 'LinkedIn', url: 'https://linkedin.com/jobs' },
        { name: 'Analytics Vidhya Jobs', url: 'https://jobs.analyticsvidhya.com' },
        { name: 'Naukri.com', url: 'https://naukri.com' },
        { name: 'Indeed India', url: 'https://indeed.co.in' },
      ],
    },
    {
      step: 3,
      title: 'Show Your Analytical Thinking Publicly',
      description: 'Publish one data analysis per month on LinkedIn or Medium. Analyze trending topics: IPL stats, startup funding, movie box office. Data insights go viral.',
      template: `Hi [Name], I came across [Company] while researching analytics roles in [industry]. I noticed your team is focused on [product/metric]. I built an analysis on [related dataset] and thought it might be interesting to you. I'm looking for a data analytics internship — would love to learn from your team. Here's my Tableau portfolio: [link]`,
    },
  ],

  resumeTips: [
    'List tools explicitly: SQL, Python (Pandas, NumPy), Tableau, Power BI, Excel',
    'Use numbers: "Analyzed 500K+ rows of sales data", "Built dashboard used by 5 departments"',
    'Mention specific databases: MySQL, PostgreSQL, BigQuery, Snowflake',
    'Include Kaggle profile and Tableau Public profile links',
    'Show business impact, not just technical output',
  ],

  linkedInTips: [
    'Post monthly data insights on trending Indian datasets (IPL, Nifty50, election results)',
    'Share "TIL in SQL" posts — hugely popular with recruiters',
    'Connect with analytics managers and data team leads at target companies',
    'Write about your data cleaning struggles — authenticity builds audience',
  ],
}
