import type { Roadmap } from '../types'

export const uiUxRoadmap: Roadmap = {
  id: 'ui-ux',
  title: 'UI/UX Design',
  tagline: 'From design thinking to a portfolio that lands jobs — 10 weeks',
  icon: 'Paintbrush',
  color: '#f472b6',
  accentGradient: 'from-pink-500 to-rose-400',
  totalWeeks: 10,
  difficulty: 'beginner-friendly',
  averageSalary: '₹3–7 LPA (fresher)',
  jobOpenings: '30,000+ open roles in India',

  phases: [
    {
      id: 'phase-1',
      phase: 1,
      title: 'Design Fundamentals',
      subtitle: 'Principles · Typography · Color · Figma',
      duration: 'Week 1–2',
      icon: 'Palette',
      color: 'pink',
      goal: 'I understand core design principles and can navigate Figma confidently',
      topics: [
        'Design principles: contrast, alignment, repetition, proximity (CARP)',
        'Typography: typeface pairing, hierarchy, readability',
        'Color theory: HSL, complementary, analogous, 60-30-10 rule',
        'Figma basics: frames, auto-layout, components, styles',
        'Grid systems and spacing (8pt grid)',
        'Gestalt principles in UI design',
      ],
      resources: [
        { title: 'Google UX Design Certificate – Coursera (Audit)', url: 'https://coursera.org/professional-certificates/google-ux-design', type: 'course', free: true },
        { title: 'Figma for Beginners – Official Tutorials', url: 'https://figma.com/resources/learn-design', type: 'course', free: true },
        { title: 'Refactoring UI (Book + Free Samples)', url: 'https://refactoringui.com', type: 'book', free: false },
        { title: 'Design Systems with Figma – Figma YouTube', url: 'https://youtube.com/@Figma', type: 'video', free: true },
        { title: 'Mobbin – UI Inspiration Library', url: 'https://mobbin.com', type: 'tool', free: true },
      ],
      projects: [
        {
          title: 'Design Fundamentals Exercises',
          description: 'Recreate 3 famous UI screens in Figma (Spotify, Airbnb, Stripe). Focus on understanding their grid, type scale, and color choices.',
          skills: ['Figma', 'Typography', 'Color', 'Layout'],
          difficulty: 'beginner',
          estimatedTime: '10–15 hours',
        },
      ],
      milestone: 'Figma file shared publicly on community with 3 recreations',
    },
    {
      id: 'phase-2',
      phase: 2,
      title: 'UX Research & Wireframing',
      subtitle: 'User Research · Personas · Information Architecture',
      duration: 'Week 3–5',
      icon: 'Users',
      color: 'rose',
      goal: 'I can identify user problems and structure solutions before jumping to UI',
      topics: [
        'UX research methods: user interviews, surveys, usability testing',
        'User personas and empathy maps',
        'User journey mapping',
        'Information architecture: card sorting, site maps',
        'Low-fidelity wireframing (pen-paper → Figma)',
        'User flows and task flows',
        'Accessibility basics (WCAG 2.1 AA)',
      ],
      resources: [
        { title: 'Nielsen Norman Group Articles (Free)', url: 'https://nngroup.com/articles/', type: 'article', free: true },
        { title: 'Laws of UX', url: 'https://lawsofux.com', type: 'article', free: true },
        { title: 'UX Collective – Medium', url: 'https://uxdesign.cc', type: 'article', free: true },
      ],
      projects: [
        {
          title: 'UX Case Study: Redesign an App',
          description: 'Pick a poorly designed app (government, bank, local business). Do 3 user interviews, identify pain points, create personas and a redesign wireframe.',
          skills: ['UX Research', 'Wireframing', 'User Personas'],
          difficulty: 'intermediate',
          estimatedTime: '20–30 hours',
        },
      ],
      milestone: 'Published case study on Notion or Medium with research + wireframes',
    },
    {
      id: 'phase-3',
      phase: 3,
      title: 'High-Fidelity UI & Prototyping',
      subtitle: 'UI Design · Design Systems · Interactive Prototypes',
      duration: 'Week 6–8',
      icon: 'Layers',
      color: 'fuchsia',
      goal: 'I can produce polished, production-ready UI and interactive prototypes',
      topics: [
        'Component-driven design in Figma (Variants, Props)',
        'Building a personal design system (colors, typography, icons, components)',
        'Micro-interactions and animation in Figma Prototype',
        'Responsive design for mobile, tablet, desktop',
        'Dark mode design considerations',
        'Design handoff to developers (Inspect, Zeplin)',
      ],
      resources: [
        { title: 'Dribbble – UI Inspiration', url: 'https://dribbble.com', type: 'tool', free: true },
        { title: 'UI.dev – Advanced Figma Techniques', url: 'https://ui.dev', type: 'course', free: false },
        { title: 'Iconify – Icon Library', url: 'https://iconify.design', type: 'tool', free: true },
        { title: 'Google Fonts', url: 'https://fonts.google.com', type: 'tool', free: true },
      ],
      projects: [
        {
          title: 'Full Product Design (End-to-End)',
          description: 'Design a complete mobile app from scratch: onboarding, home, profile, settings. Build interactive prototype with transitions.',
          skills: ['Figma', 'Prototyping', 'Component Library', 'Mobile Design'],
          difficulty: 'advanced',
          estimatedTime: '30–50 hours',
        },
      ],
      milestone: 'Portfolio-ready Figma file with components, prototype link, and Loom walkthrough',
    },
    {
      id: 'phase-4',
      phase: 4,
      title: 'Portfolio & Job Hunt',
      subtitle: 'Behance · Case Studies · Interviews',
      duration: 'Week 9–10',
      icon: 'Rocket',
      color: 'emerald',
      goal: 'My portfolio impresses recruiters and I can explain my design decisions',
      topics: [
        'Writing compelling UX case studies (problem → process → solution → impact)',
        'Building a portfolio website (Framer, Webflow, or custom)',
        'Behance and Dribbble profile optimization',
        'Common UI/UX interview questions',
        'Design challenge preparation (1-hour exercises)',
        'Presentation skills for design reviews',
      ],
      resources: [
        { title: 'Framer – Portfolio Builder', url: 'https://framer.com', type: 'tool', free: false },
        { title: 'Behance', url: 'https://behance.net', type: 'tool', free: true },
        { title: 'UX Portfolio Tips – Sarah Doody YouTube', url: 'https://youtube.com/@SarahDoody', type: 'video', free: true },
      ],
      projects: [],
      milestone: '2 published case studies, portfolio site live, 10 applications sent',
    },
  ],

  internshipGuide: [
    {
      step: 1,
      title: 'Portfolio First, Applications Second',
      description: 'In UX/UI, your portfolio IS your resume. Before applying anywhere, make sure you have at least 2 full case studies published publicly.',
    },
    {
      step: 2,
      title: 'Where to Find Design Internships',
      platforms: [
        { name: 'Internshala', url: 'https://internshala.com' },
        { name: 'LinkedIn', url: 'https://linkedin.com/jobs' },
        { name: 'Dribbble Jobs', url: 'https://dribbble.com/jobs' },
        { name: 'Behance Jobs', url: 'https://behance.net/joblist' },
        { name: 'Wellfound', url: 'https://wellfound.com' },
      ],
      description: 'Apply specifically to product-based companies, SaaS startups, and digital agencies.',
    },
    {
      step: 3,
      title: 'Cold DM on Twitter/X and LinkedIn',
      description: 'Design leaders love designers who show initiative and taste.',
      template: `Hi [Name], I've been following your work at [Company] — your [specific project/feature] has a great balance of simplicity and clarity. I'm a UI/UX student building my portfolio. I'd love to shadow or intern with your team — even remotely. Here's my portfolio: [link]`,
    },
  ],

  resumeTips: [
    'Add your portfolio link as the FIRST thing on your resume — make it clickable',
    'List design tools: Figma, Adobe XD, Principle, Framer, Zeplin',
    'Show measurable outcomes: "Redesign increased user retention by 23%"',
    'Include 2–3 case study titles as bullet points under Projects',
    'List soft skills: User Research, Stakeholder Communication, Design Thinking',
  ],

  linkedInTips: [
    'Share weekly "what I designed today" posts with before/afters',
    'Follow design leaders: Julie Zhuo, Aarron Walter, Steve Schoger',
    'Tag companies you\'d love to work for in your posts',
    'Share your case study articles natively on LinkedIn (not just links)',
  ],
}
