import type { Roadmap } from '../types'

export const webDevelopmentRoadmap: Roadmap = {
  id: 'web-development',
  title: 'Web Development',
  tagline: 'From zero to internship-ready in 12 weeks',
  icon: 'Globe',
  color: '#0ea5e9',
  accentGradient: 'from-sky-500 to-cyan-400',
  totalWeeks: 12,
  difficulty: 'beginner-friendly',
  averageSalary: '₹3–8 LPA (fresher)',
  jobOpenings: '85,000+ open roles in India',

  phases: [
    {
      id: 'phase-1',
      phase: 1,
      title: 'The Foundation',
      subtitle: 'HTML · CSS · JS Basics',
      duration: 'Week 1–2',
      icon: 'Layers',
      color: 'sky',
      goal: 'I can build and style a static website from scratch',
      topics: [
        'HTML5 semantic elements (header, main, section, article)',
        'CSS Flexbox & Grid layout systems',
        'CSS custom properties & responsive design',
        'JavaScript variables, functions, arrays, objects',
        'DOM selection & basic event handling',
        'Chrome DevTools for debugging',
      ],
      resources: [
        { title: 'The Odin Project – Foundations', url: 'https://theodinproject.com', type: 'course', free: true },
        { title: 'freeCodeCamp – Responsive Web Design', url: 'https://freecodecamp.org', type: 'course', free: true },
        { title: 'CSS Tricks – A Complete Guide to Flexbox', url: 'https://css-tricks.com/snippets/css/a-guide-to-flexbox/', type: 'article', free: true },
        { title: 'JavaScript.info', url: 'https://javascript.info', type: 'article', free: true },
        { title: 'Kevin Powell – CSS YouTube Channel', url: 'https://youtube.com/@KevinPowell', type: 'video', free: true },
      ],
      projects: [
        {
          title: 'Personal Portfolio Website',
          description: 'Build a multi-section portfolio with About, Projects, Skills, and Contact sections. Deploy on GitHub Pages.',
          skills: ['HTML', 'CSS', 'Responsive Design'],
          difficulty: 'beginner',
          estimatedTime: '8–12 hours',
        },
        {
          title: 'Product Landing Page Clone',
          description: 'Clone any popular product landing page (e.g., Notion, Linear) to practice layout and styling skills.',
          skills: ['CSS Grid', 'Flexbox', 'Typography'],
          difficulty: 'beginner',
          estimatedTime: '6–10 hours',
        },
      ],
      milestone: 'Your portfolio is live on GitHub Pages with a custom domain',
    },
    {
      id: 'phase-2',
      phase: 2,
      title: 'Going Interactive',
      subtitle: 'Advanced JS · Git · React Basics',
      duration: 'Week 3–6',
      icon: 'Zap',
      color: 'blue',
      goal: 'I can build real interactive applications and collaborate via Git',
      topics: [
        'DOM manipulation & event bubbling',
        'Fetch API & async/await (Promises)',
        'LocalStorage & JSON',
        'Git workflow: branch, commit, merge, PR',
        'GitHub – push projects, write READMEs',
        'React fundamentals: JSX, components, props, state',
        'React hooks: useState, useEffect',
        'React Router for SPA navigation',
      ],
      resources: [
        { title: 'React Official Docs – react.dev', url: 'https://react.dev', type: 'article', free: true },
        { title: 'Scrimba – Learn React for Free', url: 'https://scrimba.com/learn/learnreact', type: 'course', free: true },
        { title: 'Git & GitHub Crash Course – Traversy Media', url: 'https://youtube.com/watch?v=SWYqp7iY_Tc', type: 'video', free: true },
        { title: 'Open Weather Map API Docs', url: 'https://openweathermap.org/api', type: 'tool', free: true },
        { title: 'JavaScript30 by Wes Bos', url: 'https://javascript30.com', type: 'course', free: true },
      ],
      projects: [
        {
          title: 'To-Do App with Persistence',
          description: 'React to-do list with add/edit/delete/filter, LocalStorage persistence, and drag-to-reorder.',
          skills: ['React', 'useState', 'LocalStorage'],
          difficulty: 'intermediate',
          estimatedTime: '10–15 hours',
        },
        {
          title: 'Weather Dashboard',
          description: 'Fetch real weather data from OpenWeatherMap API. Show current + 5-day forecast with animated icons.',
          skills: ['React', 'Fetch API', 'async/await', 'CSS animations'],
          difficulty: 'intermediate',
          estimatedTime: '12–18 hours',
        },
        {
          title: 'GitHub Profile Finder',
          description: 'Search GitHub users and display repos, followers, stars using the GitHub REST API.',
          skills: ['React', 'REST API', 'React Router'],
          difficulty: 'intermediate',
          estimatedTime: '8–12 hours',
        },
      ],
      milestone: 'Three projects deployed on Vercel, all with GitHub repos with good READMEs',
    },
    {
      id: 'phase-3',
      phase: 3,
      title: 'Full-Stack Power',
      subtitle: 'Node.js · MongoDB · Auth · Deployment',
      duration: 'Week 7–10',
      icon: 'Server',
      color: 'violet',
      goal: 'I can build, deploy, and secure a full-stack web application',
      topics: [
        'Node.js fundamentals & npm ecosystem',
        'Express.js: routes, middleware, error handling',
        'REST API design (GET, POST, PUT, DELETE)',
        'MongoDB with Mongoose ODM',
        'JWT authentication & bcrypt password hashing',
        'Environment variables & .env security',
        'Vercel / Railway deployment',
        'Basic SQL with PostgreSQL (bonus)',
      ],
      resources: [
        { title: 'Node.js Official Docs', url: 'https://nodejs.org/docs', type: 'article', free: true },
        { title: 'MongoDB University – Free Courses', url: 'https://university.mongodb.com', type: 'course', free: true },
        { title: 'Full Stack Open (Helsinki University)', url: 'https://fullstackopen.com', type: 'course', free: true },
        { title: 'Postman – API Testing Tool', url: 'https://postman.com', type: 'tool', free: true },
        { title: 'Railway.app – Free Deployment', url: 'https://railway.app', type: 'tool', free: true },
      ],
      projects: [
        {
          title: 'Full-Stack Auth App',
          description: 'User registration + login with JWT, protected routes, dashboard with CRUD operations. Deploy backend + frontend separately.',
          skills: ['Node.js', 'Express', 'MongoDB', 'JWT', 'React'],
          difficulty: 'advanced',
          estimatedTime: '25–40 hours',
        },
        {
          title: 'Blog Platform CMS',
          description: 'Full-stack blog with admin panel to write/edit/delete posts, public reader view, and comment system.',
          skills: ['MERN Stack', 'Authentication', 'REST API'],
          difficulty: 'advanced',
          estimatedTime: '30–50 hours',
        },
      ],
      milestone: 'Full-stack project is live with a shareable URL, documented API, and clean codebase',
    },
    {
      id: 'phase-4',
      phase: 4,
      title: 'Internship Launch',
      subtitle: 'Resume · Portfolio · Outreach · DSA',
      duration: 'Week 11–12',
      icon: 'Rocket',
      color: 'emerald',
      goal: 'I am actively applying and getting interview calls',
      topics: [
        'ATS-optimized resume writing',
        'GitHub portfolio curation (pinned repos, READMEs)',
        'LinkedIn profile optimization (banner, about, skills)',
        'Basic DSA: arrays, strings, hashmaps, two pointers',
        'Cold outreach message writing',
        'Startup research & targeting strategy',
        'Behavioral interview preparation (STAR method)',
      ],
      resources: [
        { title: 'Internshala', url: 'https://internshala.com', type: 'tool', free: true },
        { title: 'LinkedIn Jobs', url: 'https://linkedin.com/jobs', type: 'tool', free: true },
        { title: 'Wellfound (AngelList)', url: 'https://wellfound.com', type: 'tool', free: true },
        { title: 'Naukri.com', url: 'https://naukri.com', type: 'tool', free: true },
        { title: 'LeetCode – Easy Problems', url: 'https://leetcode.com/problemset', type: 'tool', free: true },
        { title: 'Resume Worded – ATS Checker', url: 'https://resumeworded.com', type: 'tool', free: false },
      ],
      projects: [
        {
          title: 'Polish All 3–4 Projects',
          description: 'Add proper READMEs with screenshots, live demo links, tech stack badges. Record a 2-min demo video for each.',
          skills: ['Documentation', 'Markdown', 'Loom'],
          difficulty: 'beginner',
          estimatedTime: '8–12 hours',
        },
      ],
      milestone: '10 applications sent, 1 interview scheduled',
    },
  ],

  internshipGuide: [
    {
      step: 1,
      title: "Don't wait to feel 100% ready",
      description: "Apply when you're at 70% confident. Employers expect interns to learn. Waiting for perfect is the #1 reason students miss opportunities. Start applying after Phase 3.",
    },
    {
      step: 2,
      title: 'Target the right platforms',
      description: 'Different platforms serve different opportunities. Use all of them simultaneously — each has different listings.',
      platforms: [
        { name: 'Internshala', url: 'https://internshala.com' },
        { name: 'LinkedIn', url: 'https://linkedin.com/jobs' },
        { name: 'Wellfound', url: 'https://wellfound.com' },
        { name: 'Naukri.com', url: 'https://naukri.com' },
        { name: 'Instahyre', url: 'https://instahyre.com' },
        { name: 'HackerEarth Jobs', url: 'https://hackerearth.com/jobs' },
      ],
    },
    {
      step: 3,
      title: 'Cold Outreach (Most Powerful)',
      description: 'Directly messaging founders on LinkedIn works 5x better than submitting blind applications. Keep it short, specific, and genuine.',
      template: `Hi [Name], I'm a CS student learning full-stack development. I built [Project Name] — a [one-line description]. I'd love to contribute to [Company] — even as an unpaid intern — to gain real-world experience. Would you be open to a 15-minute call?`,
    },
    {
      step: 4,
      title: 'Target Startups, Not Giants',
      description: 'Early-stage startups (5–50 person companies) are 10x more likely to hire student interns. They need help, move fast, and give real ownership. Search LinkedIn for "hiring interns", "looking for contributors", "student developer".',
    },
    {
      step: 5,
      title: "DSA Won't Kill You (But Helps)",
      description: 'For internships, focus on: arrays, strings, hashmaps, two pointers, binary search. Do 20–30 LeetCode Easy problems. Most internship interviews at startups are project-focused, not DSA-heavy.',
    },
  ],

  resumeTips: [
    'Use a single-column, ATS-scannable format (no tables or columns)',
    'Put your GitHub and portfolio link prominently at the top',
    'For each project, use: Built X using Y that resulted in Z',
    'Quantify wherever possible: "reduced load time by 40%"',
    'Keep to 1 page — recruiters spend 7 seconds on a resume',
    'Use keywords from the job description verbatim',
    'List tech skills grouped by category (Languages, Frameworks, Tools)',
    'Include CGPA only if above 7.5/10',
  ],

  linkedInTips: [
    'Headline: "Aspiring Web Developer | React · Node.js · Building in Public"',
    'Post 1 project update per week with screenshots (massive visibility)',
    'Connect with developers at target companies BEFORE applying',
    'Engage on posts by CTOs and founders of target startups',
    'Add "Open to Internships" in the job preferences section',
    'Get 3 skill endorsements from peers or mentors',
  ],
}
